# Generated by Django 4.1.7 on 2024-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_unpaiduser_full_name_unpaiduser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiduser',
            name='has_finished',
            field=models.BooleanField(default=False),
        ),
    ]
