# Generated by Django 4.1.7 on 2024-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_programmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmap',
            name='image',
            field=models.FileField(upload_to='static/program_images', verbose_name='Изображения'),
        ),
    ]
