# Generated by Django 4.1.7 on 2024-04-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_programmap_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='категории',
            options={'verbose_name': 'Категории'},
        ),
    ]
