# Generated by Django 4.1.7 on 2024-04-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_категории_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='категории',
            options={},
        ),
    ]
